### ISSUE TITLE
[Bug] Hover on bubbles cause them to shrink

### ISSUE THREAD

**Issue by apertureless** [daboth/pive#4] opened 2016-03-29 18:12 UTC
If you hover over the bubbles, they shrink.
It seems thats a problem with the highlighting, because the object scales down, but does not scale up again.

![bubble](https://cloud.githubusercontent.com/assets/4975917/14118554/48aa6436-f5ea-11e5-874e-829e608e83f4.gif)

**Comment by daboth** [comment] 2016-03-30 12:01
Thank you for the detailed visual report. I did not encounter this myself, but will definitely take a closer look at the bubblechart template. Did you use some specific parameters?

**Comment by apertureless** [comment] 2016-03-31 08:03
Here are the settings: 
<img width="1077" alt="bildschirmfoto 2016-03-31 um 10 02 39" src="https://cloud.githubusercontent.com/assets/4975917/14169401/d346af94-f727-11e5-83c8-a912864489fe.png">

**Comment by apertureless** [comment] 2016-03-31 08:04
I think its because of the highlightfactor somehow. :dancer:

**Comment by daboth** [comment] 2016-04-04 13:02
The problem is not directly linked to the hightlight factor. I think the transitions are not locked in this template. When another transistion starts, D3 does not complete the currently active transition, so the bubbles just stop resizing when you hit another one. It only occurs if you swipe the mouse really fast across the datapoints. I will put this on my list as a mayor bug.

**Comment by daboth** [comment] 2016-05-10 11:41
Fixed with 82b67e8d4270543ef3563ff81a758773de6306b2

**Closed as completed by daboth** 2016-05-10 11:41 UTC
